name = "proxytt"
main = "workers/proxytt.entry.js"
compatibility_date = "2026-02-23"
account_id = "7f416be9fa20a235cafa1a13ab01b80d"

# Routes are managed in the Cloudflare dashboard (if any).
workers_dev = true

